services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: timed
      POSTGRES_PASSWORD: timed
      POSTGRES_DB: timed
    volumes:
      - timed_dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5433}
    ports:
      - 5433:5433

volumes:
  timed_dbdata:
    external: true