services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: timed
      POSTGRES_PASSWORD: timed
      POSTGRES_DB: timed
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}
    ports:
      - 5432:5432

volumes:
  dbdata: