services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}
    ports:
      - 5432:5432

volumes:
  db_data: