defmodule Timed.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    create table(:tracking_report) do
      add :comment, :text, null: false
      add :duration, :interval, null: false
      add :not_billable, :boolean, null: false
      add :billed, :boolean, null: false
      add :date, :date, null: false
      add :task_id, :bigint
      add :user_id, :bigint
      add :verified_by_id, :bigint
      add :review, :boolean, null: false, default: false
      add :rejected, :boolean, null: false, default: false
      add :added, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tracking_attendance, primary_key: false) do
      add :id, :bigint, null: false, primary_key: true
      add :date, :date, null: false
      add :from_time, :time, null: false
      add :to_time, :time, null: false
      add :user_id, :bigint, null: false
    end

    create table(:tracking_activity, primary_key: false) do
      add :id, :bigint, null: false, primary_key: true
      add :comment, :text, null: false
      add :date, :date, null: false
      add :task_id, :bigint
      add :user_id, :bigint, null: false
      add :transferred, :boolean, null: false
      add :from_time, :time, null: false
      add :to_time, :time
      add :not_billable, :boolean, null: false
      add :review, :boolean, null: false
    end

    create table(:tracking_absence, primary_key: false) do
      add :id, :bigint, null: false, primary_key: true
      add :comment, :text, null: false
      add :date, :date, null: false
      add :absence_type_id, :bigint, null: false
      add :user_id, :bigint, null: false
    end

    create unique_index(:tracking_absence, [:date, :user_id],
             name: "tracking_absence_date_user_id_96b8708e_uniq"
           )

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projects_task, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:tracking_report) do
      modify :task_id,
             references(:projects_task,
               column: :id,
               name: "tracking_report_task_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:projects_task) do
      add :name, :text, null: false
      add :reference, :text
      add :archived, :boolean, null: false, default: false
      add :estimated_time, :interval
      add :cost_center_id, :bigint, null: false
      add :project_id, :bigint, null: false
    end

    create table(:projects_project) do
      add :name, :text, null: false
      add :reference, :text
      add :comment, :text, null: false
      add :archived, :boolean, null: false, default: false
      add :billed, :boolean, null: false, default: false
      add :estimated_time, :interval
      add :customer_visible, :boolean, null: false, default: false
      add :remaining_effort_tracking, :boolean, null: false, default: false
      add :total_remaining_effort, :interval, null: false
      add :customer_id, :bigint, null: false
      add :billing_type_id, :bigint, null: false
      add :cost_center_id, :bigint, null: false
    end

    create table(:projects_customerassignee, primary_key: false) do
      add :id, :bigint, null: false, primary_key: true
      add :is_resource, :boolean, null: false
      add :is_reviewer, :boolean, null: false
      add :is_manager, :boolean, null: false
      add :user_id, :bigint, null: false
      add :is_customer, :boolean, null: false
      add :customer_id, :bigint, null: false
    end

    create table(:projects_customer, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:projects_project) do
      modify :customer_id,
             references(:projects_customer,
               column: :id,
               name: "projects_project_customer_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:projects_customerassignee) do
      modify :customer_id,
             references(:projects_customer,
               column: :id,
               name: "projects_customerassignee_customer_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:projects_customer, primary_key: false) do
      add :name, :text, null: false
      add :email, :text, null: false
      add :website, :text, null: false
      add :comment, :text, null: false
      add :archived, :boolean, null: false
      add :reference, :text
    end

    create index(:projects_customer, [:reference],
             name: "projects_customer_reference_3d93d989_like"
           )

    create index(:projects_customer, [:name], name: "projects_customer_name_5adc47bc_like")

    create unique_index(:projects_customer, [:name], name: "projects_customer_name_5adc47bc_uniq")

    create table(:projects_costcenter)

    alter table(:projects_task) do
      modify :cost_center_id,
             references(:projects_costcenter,
               column: :id,
               name: "projects_task_cost_center_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :project_id,
             references(:projects_project,
               column: :id,
               name: "projects_task_project_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:projects_costcenter) do
      add :name, :text, null: false
      add :reference, :text
    end

    create index(:projects_costcenter, [:name], name: "projects_costcenter_name_6a787b98_like")

    create unique_index(:projects_costcenter, [:name], name: "projects_costcenter_name_key")

    create table(:projects_billingtype)

    alter table(:projects_project) do
      modify :billing_type_id,
             references(:projects_billingtype,
               column: :id,
               name: "projects_project_billing_type_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :cost_center_id,
             references(:projects_costcenter,
               column: :id,
               name: "projects_project_cost_center_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:projects_billingtype) do
      add :name, :text, null: false
      add :reference, :text
    end

    create index(:projects_billingtype, [:name], name: "projects_billingtype_name_945d6bac_like")

    create unique_index(:projects_billingtype, [:name], name: "projects_billingtype_name_key")

    create table(:employment_user, primary_key: false) do
      add :id, :bigint, null: false, primary_key: true
    end

    alter table(:tracking_report) do
      modify :user_id,
             references(:employment_user,
               column: :id,
               name: "tracking_report_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:employment_user) do
      add :password, :text, null: false
      add :last_login, :utc_datetime_usec
      add :is_superuser, :boolean, null: false
      add :username, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :email, :text, null: false
      add :is_staff, :boolean, null: false
      add :is_active, :boolean, null: false
      add :date_joined, :utc_datetime_usec, null: false
      add :tour_done, :boolean, null: false
      add :is_accountant, :boolean, null: false
    end

    create index(:employment_user, [:username], name: "employment_user_username_f3762b2b_like")

    create unique_index(:employment_user, [:username], name: "employment_user_username_key")
  end

  def down do
    drop_if_exists unique_index(:employment_user, [:username],
                     name: "employment_user_username_key"
                   )

    drop_if_exists index(:employment_user, [:username],
                     name: "employment_user_username_f3762b2b_like"
                   )

    alter table(:employment_user) do
      remove :is_accountant
      remove :tour_done
      remove :date_joined
      remove :is_active
      remove :is_staff
      remove :email
      remove :last_name
      remove :first_name
      remove :username
      remove :is_superuser
      remove :last_login
      remove :password
    end

    drop constraint(:tracking_report, "tracking_report_user_id_fkey")

    alter table(:tracking_report) do
      modify :user_id, :bigint
    end

    drop table(:employment_user)

    drop_if_exists unique_index(:projects_billingtype, [:name],
                     name: "projects_billingtype_name_key"
                   )

    drop_if_exists index(:projects_billingtype, [:name],
                     name: "projects_billingtype_name_945d6bac_like"
                   )

    alter table(:projects_billingtype) do
      remove :reference
      remove :name
    end

    drop constraint(:projects_project, "projects_project_billing_type_id_fkey")

    drop constraint(:projects_project, "projects_project_cost_center_id_fkey")

    alter table(:projects_project) do
      modify :cost_center_id, :bigint
      modify :billing_type_id, :bigint
    end

    drop table(:projects_billingtype)

    drop_if_exists unique_index(:projects_costcenter, [:name],
                     name: "projects_costcenter_name_key"
                   )

    drop_if_exists index(:projects_costcenter, [:name],
                     name: "projects_costcenter_name_6a787b98_like"
                   )

    alter table(:projects_costcenter) do
      remove :reference
      remove :name
    end

    drop constraint(:projects_task, "projects_task_cost_center_id_fkey")

    drop constraint(:projects_task, "projects_task_project_id_fkey")

    alter table(:projects_task) do
      modify :project_id, :bigint
      modify :cost_center_id, :bigint
    end

    drop table(:projects_costcenter)

    drop_if_exists unique_index(:projects_customer, [:name],
                     name: "projects_customer_name_5adc47bc_uniq"
                   )

    drop_if_exists index(:projects_customer, [:name],
                     name: "projects_customer_name_5adc47bc_like"
                   )

    drop_if_exists index(:projects_customer, [:reference],
                     name: "projects_customer_reference_3d93d989_like"
                   )

    alter table(:projects_customer) do
      remove :reference
      remove :archived
      remove :comment
      remove :website
      remove :email
      remove :name
    end

    drop constraint(:projects_customerassignee, "projects_customerassignee_customer_id_fkey")

    alter table(:projects_customerassignee) do
      modify :customer_id, :bigint
    end

    drop constraint(:projects_project, "projects_project_customer_id_fkey")

    alter table(:projects_project) do
      modify :customer_id, :bigint
    end

    drop table(:projects_customer)

    drop table(:projects_customerassignee)

    drop table(:projects_project)

    alter table(:projects_task) do
      remove :project_id
      remove :cost_center_id
      remove :estimated_time
      remove :archived
      remove :reference
      remove :name
    end

    drop constraint(:tracking_report, "tracking_report_task_id_fkey")

    alter table(:tracking_report) do
      modify :task_id, :bigint
    end

    drop table(:projects_task)

    drop table(:tokens)

    drop_if_exists unique_index(:tracking_absence, [:date, :user_id],
                     name: "tracking_absence_date_user_id_96b8708e_uniq"
                   )

    drop table(:tracking_absence)

    drop table(:tracking_activity)

    drop table(:tracking_attendance)

    drop table(:tracking_report)

    drop table(:users)
  end
end
